name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
jobs:

  build:
    permissions: write-all # important!

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract Version
      id: version
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
     
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: schack
        password: ${{ secrets.PUSH_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ghcr.io/schack/cloudflare-d1-backup:${{ steps.version.outputs.version }} .
    
    - name: Push the Docker image to ghcr.io
      run: |
         docker push ghcr.io/schack/cloudflare-d1-backup:${{ steps.version.outputs.version }}
         docker tag ghcr.io/schack/cloudflare-d1-backup:${{ steps.version.outputs.version }} ghcr.io/schack/cloudflare-d1-backup:latest
         docker push ghcr.io/schack/cloudflare-d1-backup:latest

